version: '2'
services:
  data:
    image: tianon/true
    container_name: data
    volumes:
      - ./../www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    volumes_from:
      - data
    ports:
      - 80:80
      - 443:443
    links:
      - php
  php:
    build:
      context: ./php
      dockerfile: php-7.0.32-fpm-stretch.dockerfile
    container_name: php-7
    hostname: php
    restart: always
    volumes_from:
      - data
    expose:
      - 9000
    links:
      - mariadb
      - mongodb
      - elasticsearch
      - memcached
      - mailhog
    env_file:
      - ./.env
  mariadb:
    image: mariadb:10.0.36
    container_name: mariadb
    hostname: mariadb
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mariadbdata:/var/lib/mysql
    env_file:
      - ./.env
  mongodb:
    image: mongo:3.6.8
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    env_file:
      - ./.env
  elasticsearch:
    image: blacktop/elasticsearch:6.1
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
  memcached:
    image: memcached:alpine
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mongodbdata:
  mariadbdata:
  elasticdata: